# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: minio-pv
#   # namespace: lakehouse
#   labels:
#       app: minio
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Gi
#   accessModes:
#   - ReadWriteOnce
#   hostPath:
#     path: "/home/dcscience/data-lakehouse-k8s/minio"
#     # type: Directory

apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    app: minio
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/home/dcscience/data-lakehouse-k8s/minio"
  # nfs:
  #   path: /home/dcscience/data-lakehouse-k8s/minio 
  #   server: 192.168.51.140         
