apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebooks-pv
  labels:
    app: notebook
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  #hostPath:
    #path: "/spark/data"
    #path: "/home/jovyan/workspace"
  nfs:
    path: "/data"
    server: 192.168.32.161
