# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: notebooks-pv
#   # namespace: lakehouse
#   labels:
#       app: notebook
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/home/dcscience/data-lakehouse-k8s/workspace"
#     # type: Directory

apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebooks-pv
  labels:
    app: notebook
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/dcscience/data-lakehouse-k8s/workspace"
  # nfs:
  #   path: /home/dcscience/data-lakehouse-k8s/workspace
  #   server: 192.168.51.140
