# old code
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: lakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: sk97/spark-master-custom:latest
        env:
        - name: SPARK_MODE
          value: "master"
        - name: SPARK_MASTER_PORT
          value: "7077"
        - name: SPARK_MASTER_WEBUI_PORT
          value: "8080"
        ports:
        - containerPort: 7077
        - containerPort: 8080
        volumeMounts:
        - name: spark-defaults
          mountPath: /opt/spark/conf
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: spark-defaults
        configMap:
          name: spark-master-config
