apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
    #namespace: lakehouse
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: awsstudydev19@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubecert-spark
  namespace: lakehouse
spec:
  secretName: kubecert-spark
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: spark.com
  dnsNames:
  - spark.com
  - lakehouse.spark.com
  - lakehouse1.spark.com
  - lakehouse2.spark.com
