apiVersion: v1
kind: Secret
metadata:
  namespace: lakehouse
  labels:
    app: minio
  name: minio-root
type: Opaque

data:
  ROOT_USERNAME: <base64 encrypted>
  ROOT_PASSWORD: <base64 encrypted>

---

apiVersion: v1
kind: Secret
metadata:
  namespace: lakehouse
  labels:
    app: minio
  name: minio-access-key
type: Opaque

data:
  ACCESS_KEY: <base64 encrypted>
  SECRET_KEY: <base64 encrypted>
