apiVersion: v1
kind: Secret
metadata:
  namespace: lakehouse
  labels:
    app: minio
  name: minio-root
type: Opaque

data:
  ROOT_USERNAME: bWluaW8K
  ROOT_PASSWORD: bWluaW8xMjMK

---

apiVersion: v1
kind: Secret
metadata:
  namespace: lakehouse
  labels:
    app: minio
  name: minio-access-key
type: Opaque

data:
  ACCESS_KEY: bWluaW8K
  SECRET_KEY: bWluaW8xMjMK
